#!/usr/bin/env node
/* Writes stripe-checkout/catalog.mjs from lunara-pricing.js.

     node stripe-checkout/build-catalog.mjs

   The checkout function charges what catalog.mjs says, never what the
   browser says. lunara-pricing.js stays the only place a price is
   written; this copies it into a file the edge function can import.
   test_checkout.mjs fails in CI if the two disagree, so a price change
   that is not rebuilt and redeployed stops the deploy. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

/* Not sold through Stripe Checkout: invitational products go only to
   people who have been accepted, and Lens plans are paid in the app so
   the credits reach the account that paid. */
export function sellable(p) {
  return !p.invitational && !p.id.startsWith('lens');
}

export function loadPricing() {
  const src = readFileSync(fileURLToPath(new URL('../lunara-pricing.js', import.meta.url)), 'utf8');
  const window = {};
  vm.runInNewContext(src, { window, document: { readyState: 'complete', querySelectorAll: () => [] } });
  return window.LunaraPricing.products;
}

export function catalogFrom(products) {
  const out = {};
  for (const p of products.filter(sellable)) {
    out[p.id] = { name: p.name, cents: Math.round(p.price * 100), terms: p.terms };
  }
  return out;
}

export function render(catalog) {
  return `/* Generated by build-catalog.mjs from lunara-pricing.js. Do not edit. */
export const CATALOG = ${JSON.stringify(catalog, null, 2)};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const file = fileURLToPath(new URL('./catalog.mjs', import.meta.url));
  writeFileSync(file, render(catalogFrom(loadPricing())));
  console.log('wrote', file);
}
