/* Generated by build-catalog.mjs from lunara-pricing.js. Do not edit. */
export const CATALOG = {
  "disclose": {
    "name": "Article 50 Disclosure Pack",
    "cents": 7500,
    "terms": "Delivered within 24 hours"
  },
  "kit": {
    "name": "Compliance Kit",
    "cents": 9500,
    "terms": "Immediate download"
  },
  "shield": {
    "name": "Shield Verification",
    "cents": 7500,
    "terms": "Six months. Renewed by invoice, never auto-charged."
  },
  "second": {
    "name": "Second Opinion",
    "cents": 24000,
    "terms": "Returned within 48 hours"
  },
  "cir": {
    "name": "Compliance Intelligence Report",
    "cents": 39000,
    "terms": "Delivered within 24 hours"
  },
  "watch": {
    "name": "Regulatory Watch",
    "cents": 29000,
    "terms": "Six months. Renewed by invoice, never auto-charged."
  },
  "cirplus": {
    "name": "Report with Governance Session",
    "cents": 74000,
    "terms": "Scheduled within 48 hours"
  },
  "agent": {
    "name": "AI Entity Verification",
    "cents": 54000,
    "terms": "Six months. Renewed by invoice, never auto-charged."
  },
  "clinical": {
    "name": "Clinical AI Governance Assessment",
    "cents": 195000,
    "terms": "Per deployment. Delivered within five working days."
  },
  "evidence": {
    "name": "Article 50 Evidence Pack",
    "cents": 245000,
    "terms": "Per system. Delivered within five working days."
  },
  "vendor": {
    "name": "Vendor Certification",
    "cents": 740000,
    "terms": "Up to three systems. Twelve months, so it cannot lapse mid-tender. Renewed by invoice."
  }
};
